apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels: 
    app: wordpress
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: k3s.io/hostname
                operator: In
                values:
                - node02
                - node06
      #        podAffinity:
      #          preferredDuringSchedulingIgnoredDuringExecution:
      #          - weight: 100
      #            podAffinityTerm:
      #              labelSelector:
      #                matchExpressions:
      #                - key: app
      #                  operator: In
      #                  values:
      #                  - mysql
      #              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: wordpress
          image: wordpress:php7.4
          imagePullPolicy: "Always"
          envFrom:
          - configMapRef:
              name: wordpress-config
          - secretRef:
              name: wordpress-db-user-creds
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-pv
              #      nodeSelector:
              #        k3s.io/hostname: "node06"
      volumes:
        - name: wordpress-pv
          persistentVolumeClaim:
            claimName: wordpress-pvc
