apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels: 
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - bitbucket
                  - bamboo
                  - nextcloud
                  key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - jellyfin
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mysql
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: wordpress
          image: wordpress:php7.4
          envFrom:
          - configMapRef:
              name: wordpress-config
          - secretRef:
              name: wordpress-db-user-creds
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-pv
      volumes:
        - name: wordpress-pv
          persistentVolumeClaim:
            claimName: wordpress-pvc
